# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-config
#   labels:
#     db: blog-postgres
# data:
#   init.sql: |
#     CREATE DATABASE blogdb;

# ---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-postgres
  labels:
    db: blog-postgres
spec:
  selector:
    matchLabels:
      db: blog-postgres
  template:
    metadata:
      labels:
        db: blog-postgres
    spec:
      containers:
        - name: blog-postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password 
            - name: POSTGRES_DB
              value: blogdb
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi    
          volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim    

---

apiVersion: v1
kind: Service
metadata:
  name: blog-postgres
  labels:
    db: blog-postgres
spec:
  type: ClusterIP
  selector:
    db: blog-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
