apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-service
  labels:
    app: userprofile-service
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: userprofile-service 
  template:
    metadata: 
      labels:
        app: userprofile-service 
    spec: 
      containers:
      - name: userprofile-service
        image: ranjithdoc/userprofile-service
        imagePullPolicy: IfNotPresent
        lifecycle: 
            preStop:
              exec: 
                command: [ "sh", "-c", "sleep 5" ]
        ports: 
          - containerPort: 9010
        env:
          - name: BPL_JVM_THREAD_COUNT
            value: "50" 
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://blog-postgres:5432/blogdb
          - name: SPRING_DATASOURCE_USERNAME
            value: user
          - name: SPRING_DATASOURCE_PASSWORD
            value: password       
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://config-service
