version: "3.8"
services:

  # Applications

  userprofile-service:
    depends_on:
      - config-service  
      - blog-postgres
    image: "ranjithdoc/userprofile-service"
    container_name: "userprofile-service"
    ports:
      - 9010:9010
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://blog-postgres:5432/blogdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      
  edge-service:
    depends_on:
      - config-service   
      - blog-postgres
    image: "ranjithdoc/edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
    environment:
      - USERPROFILE_SERVICE_URL=http://userprofile-service:9010
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      
  config-service:
    image: "ranjithdoc/config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50  
 
 
  # Backing Services

  blog-postgres:
    image: "postgres:latest"
    container_name: "blog-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blogdb      
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database_data:/var/lib/postgresql/data
volumes:
  database_data:
    driver: local