apiVersion: v1
kind: Service
metadata:
  name: post-service
  labels:
    app: post-service
spec:
  type: ClusterIP
  selector:
    app: post-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9020